Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Management;
using System.Web.Mvc;
using ToDoApp.Models;
using ToDoApp.Services;

namespace ToDoApp.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        public readonly ToDoService toDoService;

        public readonly UserService userService;
        public ToDoController(ToDoService _toDoService)
        {
            toDoService = _toDoService;
        }


        public ActionResult Search(string searchQuery)
        {
            ViewBag.SearchQuery = searchQuery;

            if (string.IsNullOrEmpty(searchQuery))
            {
                return PartialView("_SearchResults",new List<ToDoModel>());
            }
            var todos = toDoService.GetByName(searchQuery);
            return PartialView("_SearchResults", todos != null ? new List<ToDoModel> { todos } : new List<ToDoModel>());
            //if (!string.IsNullOrEmpty(searchQuery))
            //{
            //    ViewBag.SearchQuery = searchQuery;
            //    return View(todos);
            //}
            //return View(todos);
        }

        public ActionResult Index()
        {
            var username = User.Identity.Name;
            //var user = userService.GetUserByUsername(username);
            //if (user != null)
            //{
                var todos = toDoService.GetAll();
                if (todos == null)
                {
                    Debug.WriteLine("No Todos found");
                    todos = new List<ToDoModel>();
                }
                return View(todos);

            //}
            //return RedirectToAction("Login", "AuthUser");

        }

        public ActionResult Create(int? id)
        {
            ToDoModel model = new ToDoModel();

            if (id.HasValue)
            {
                model = toDoService.GetToDoById(id.Value);

                if(model == null)
                {
                    TempData["ErrorMessage"] = "ToDo Not Found";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ToDo/Create")]
        public ActionResult Create(ToDoModel todo)
        {
            if (ModelState.IsValid)
            {
                string currentUser = User.Identity.Name;
                if(todo.Id == 0)
                {
                    todo.CreatedBy = currentUser;
                    todo.CreatedDate = DateTime.Now;
                    todo.EditedBy = "-";
                    
                    toDoService.AddToDo(todo);

                    TempData["SuccessMessage"] = "To Do added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    var existingToDo = toDoService.GetToDoById(todo.Id);

                    if (existingToDo == null)
                    {
                        TempData["ErrorMessage"] = "ToDo not found, unable to update.";
                        return RedirectToAction("Index");
                    }

                    existingToDo.EditedBy = currentUser;
                    existingToDo.EditedDate = DateTime.Now;
                    existingToDo.Title = todo.Title;
                    existingToDo.Description = todo.Description;
                    
                    toDoService.UpdateToDo(existingToDo);

                    TempData["SuccessMessage"] = "ToDo updated successfully.";
                }
                return RedirectToAction("Index");
            }
            TempData["ErrorMessage"] = "Failed to create the To Do";
            return View(todo);
        }

        //[HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    var existingToDo = toDoService.GetToDoById(id);
        //    if (existingToDo == null)
        //    {
        //        TempData["ErrorMessage"] = "ToDo not found.";
        //        return RedirectToAction("Index"); // Redirect back to the Index page
        //    }
        //    return View(existingToDo);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Route("ToDo/Edit/{id}")]
        //public ActionResult Edit(int id, ToDoModel toDoModel)
        //{
        //    if (toDoModel == null)
        //    {
        //        TempData["ErrorMessage"] = "Invalide ToDo Data";
        //        return RedirectToAction("Index");
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        var existingToDo = toDoService.GetToDoById(id);

        //        if (existingToDo == null)
        //        {
        //            TempData["ErrorMessage"] = "ToDo not found, unable to update.";
        //            return RedirectToAction("Index");
        //        }

        //        existingToDo.Title = toDoModel.Title;
        //        existingToDo.Description = toDoModel.Description;
        //        existingToDo.EditedDate = DateTime.Now;
        //        existingToDo.EditedBy = "Nera";

        //        toDoService.UpdateToDo(existingToDo);

        //        TempData["SuccessMessage"] = "ToDo updated successfully.";
        //        return RedirectToAction("Index");
        //    }
        //    TempData["ErrorMessage"] = "Data table error";
        //    return RedirectToAction("Index");
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ToDo/Delete/{id}")]
        public ActionResult Delete(int id)
        {

            toDoService.DeleteToDo(id);
            TempData["SuccessMessage"] = $"Deleted todo Successfully: {id}";
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/ToDo/Create.cshtml
@model ToDoApp.Models.ToDoModel
@{
    ViewBag.Title = "Create";
}
<!--Add new todos-->
<div class="container">
    <div class="col-md-4">
        <div class="d-flex justify-content-between">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@((Model.Id == 0)? "Add new todo":"Edit To Do") </h5>
                    @using (Html.BeginForm("Create", "ToDo", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        if (Model.Id != 0)
                        {
                            @Html.HiddenFor(m => m.Id)
                        }
                        <div class="form-group">
                            @Html.LabelFor(m => m.Title)
                            @Html.TextBoxFor(m => m.Title, null, new { @class = "form-control", placeholder = "Title", required = "required" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(x => x.Description)
                            @Html.TextArea("Description", null, new { @class = "form-control", placeholder = "Description" })
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="d-flex justify-content-between">
                                    <button type="submit" class="btn btn-primary">
                                        @((Model.Id ==0 )?"Add":"Update")
                                    </button>
                                    <a href="@Url.Action("Index", "ToDo")" class="btn btn-secondary btn-danger">Close</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/ToDo/Index.cshtml
@model  List<ToDoApp.Models.ToDoModel>
    @{ViewBag.Title = "ToDo"; }

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <form method="get" action="@Url.Action("Search", "ToDo")" class="mb-3">
        <div class="row">
            <div class="col-md-4">
                <div class="input-group">
                    <div class="form-outline" data-mdb-input-init>
                        <input type="search" name="searchQuery" id="form1" class="form-control" placeholder="Search For To Do" value="@ViewBag.SearchQuery" />
                    </div>
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary" data-mdb-ripple-init>Search</button>
                        <a href="@Url.Action("Index", "ToDo")" class="btn btn-secondary ml-2">Clear</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
    @if (!string.IsNullOrEmpty(ViewBag.SearchQuery))
    {
        if (Model.Any())
        {
            <div class="row">
                @foreach (var toDo in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">@toDo.Title</h5>
                                <p class="card-text">@toDo.Description</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    }
    else
    {
        <p class="text-muted">No matching results</p>
    }
    @if (Model == null)
    {
        <p style="color:red">Model is Null</p>
    }


    <div class="row">
        <div class="col-md-4">
            <div class="card text-bg-info text-center">
                <div class="card-body d-flex flex-column align-items-center justify-content-center">
                    <a href="@Url.Action("Create", "ToDo")" class="nav-link text-dark">
                        <i class="bi bi-plus-square fs-1"></i>
                    </a>
                </div>
            </div>
        </div>
        @for (int i = 0; i < Model.Count; i++)
        {
            var todo = Model[i];

            <div class="col-md-4">
                <div class="d-flex justify-content-between">
                    <div class="card" id="todoCard-@todo.Id">
                        <div class="card-body">
                            <div>
                                <h5 class="card-title">@todo.Title</h5>
                                <p class="card-text">@todo.Description</p>
                                <p class="card-text">Created By: @todo.CreatedBy</p>
                                <p class="card-text">Created At: @todo.CreatedDate</p>
                                <p class="card-text">Edited By: @todo.EditedBy</p>
                                <p class="card-text">Edited At: @todo.EditedDate</p>

                                <div class="row">
                                    <div class="col">
                                        <div class="d-flex justify-content-between">
                                            <a href="@Url.Action("Create","ToDo", new { id = todo.Id})" class="btn btn-warning btn-sm">Edit</a>

                                            @using (Html.BeginForm("Delete", "ToDo", FormMethod.Post))
                                            {
                                                @Html.AntiForgeryToken()
                                                @Html.Hidden("id", todo.Id)
                                                <button class="btn btn-danger btn-sm" onclick="return confirm('Delete To Do?');">Delete</button>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>