Controllers/AuthUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using System.Web.Security;
using ToDoApp.Services;
using System.Web.UI.WebControls;
using ToDoApp.Models;
using Microsoft.AspNet.Identity;
using System.Net;

namespace ToDoApp.Controllers
{
    public class AuthUserController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        public ActionResult Login(string returnUrl)
        {
            if (!_context.Users.Any())
            {
                return RedirectToAction("CreateFirstUser");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            var user = _context.Users.FirstOrDefault(u => u.UserName == username);

            if (user != null)
            {
                var passwordHasher = new PasswordHasher();
                var result = passwordHasher.VerifyHashedPassword(user.PasswordHash, password);

                if (result == Microsoft.AspNet.Identity.PasswordVerificationResult.Success)
                {
                    var authTicket = new FormsAuthenticationTicket(
                        1,
                        user.UserName,
                        DateTime.Now, 
                        DateTime.Now.AddMinutes(30),
                        false,
                        user.Role
                        );
                   
                    // Encrypt the ticket
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);

                    // Create the authentication cookie
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    Response.Cookies.Add(authCookie);

                    return RedirectToAction("Index", "ToDo");
                }
            }
            ModelState.AddModelError("", "Invalid username or password");
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login","");
        }

        public ActionResult CreateFirstUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateFirstUser(UserModel model, string password)
        {
            if (!_context.Users.Any()) // Ensure only first user gets Admin role
            {
                var passwordHasher = new Microsoft.AspNet.Identity.PasswordHasher();
                model.PasswordHash = passwordHasher.HashPassword("123");
                model.Role = "Admin"; // First user is Admin
                model.UserName = "Admin";
                _context.Users.Add(model);
                _context.SaveChanges();

                FormsAuthentication.SetAuthCookie(model.UserName, false);
                return RedirectToAction("Index", "ToDo");
            }
            return RedirectToAction("Login");
        }
    }
}

Views/AuthUser/CreateFirstUser.cshtml
@{
    ViewBag.Title = "CreateFirstUser";
}
@model ToDoApp.Models.UserModel

<h2>Create First User</h2>

@using (Html.BeginForm("CreateFirstUser", "AuthUser", FormMethod.Post))
{
    <label>Username:</label>
    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })

    <label>Password:</label>
    <input type="password" name="password" class="form-control" />

    <button type="submit" class="btn btn-primary">Create</button>
}

Views/AuthUser/Login.cshtml
@model ToDoApp.Models.UserModel
@{
    ViewBag.Title = "Login";
}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
            <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                            <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                            @using (Html.BeginForm("Login", "AuthUser", FormMethod.Post))
                            {

                                <div class="d-flex flex-row align-items-center mb-4">
                                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                    <div data-mdb-input-init class="form-outline flex-fill mb-0">                                        
                                        <input type="text" name="username" id="UserName" class="form-control" placeholder="Username" required="required" />

                                        <label class="form-label" for="form3Example1c">Username</label>
                                    </div>
                                </div>

                                <div class="d-flex flex-row align-items-center mb-4">
                                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                    <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                        <input type="password" name="password" id="PasswordHash" class="form-control" placeholder="Password" required="required"/>
                                        <label class="form-label" for="form3Example4c">Password</label>
                                    </div>
                                </div>

                                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg">Login</button>
                                </div>

                            }
                            @if (!ViewData.ModelState.IsValid)
                            {
                                <div class="alert alert-danger mt-3">
                                    @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                                    {
                                        <p>@error.ErrorMessage</p>
                                    }
                                </div>
                            }
                        </div>
                        <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                 class="img-fluid" alt="Sample image">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.history.pushState(null, "", window.location.href);
    window.onpopstate = function () {
        window.location.href = "/AuthUser/Login";
    };
</script>